name: 'icestudio'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3,6'

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:
  doc:
    runs-on: ubuntu-latest
    name: 'ğŸ““ Docs'
    steps:
      - name: 'ğŸ§° Checkout'
        uses: actions/checkout@v2

      - name: 'ğŸ Setup Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: 'ğŸ““ BuildTheDocs (BTD)'
        uses: buildthedocs/btd@v0
        with:
          token: ${{ github.token }}

      - name: 'ğŸ“¤ Upload artifact: HTML'
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/_build/html

  linwin:
    needs: [doc]
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          [
            {label: 'ğŸ§ Ubuntu', os: ubuntu, arg: lin, larg: linux},
            {label: 'ğŸ§Š Windows', os: windows, arg: win, larg: win},
          ]
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.label }}
    steps:
      - name: 'âš™ï¸ git config autocrlf'
        run: git config --global core.autocrlf input
        shell: bash

      - name: 'ğŸ§° Checkout'
        uses: actions/checkout@v2

      - name: 'âš™ï¸ Setup Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: 'â–¶ï¸ yarn'
        run: yarn

      - name: 'â–¶ï¸ check'
        run: yarn run check

      - name: 'ğŸ“¥ Download artifact: HTML'
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs/_build/html

      - name: 'â–¶ï¸ dist'
        run: yarn dist -v
        env:
          DIST_TARGET: ${{ matrix.arg }}

      - name: 'ğŸ“¤ Upload artifact: 64 bit'
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.arg }}64
          path: dist/*${{ matrix.larg }}64.zip

      - name: 'ğŸ“¤ Upload artifact: 32 bit'
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.arg }}32
          path: dist/*${{ matrix.larg }}32.zip

  mac:
    needs: [doc]
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include: [{ver: '10.15', name: Catalina}, {ver: '11.0', name: BigSur}]
    runs-on: macos-${{ matrix.ver }}
    name: 'ğŸ macOS Â· ${{ matrix.name }}'
    steps:
      - name: 'ğŸ§° Checkout'
        uses: actions/checkout@v2

      - name: 'âš™ï¸ Setup Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: 'â–¶ï¸ yarn'
        run: yarn

      - name: 'â–¶ï¸ check'
        run: yarn run check

      - name: 'ğŸ“¥ Download artifact: HTML'
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs/_build/html

      - name: 'â–¶ï¸ dist'
        run: yarn dist -v
        env:
          DIST_TARGET: osx

      - name: 'ğŸ“¤ Upload artifact: 64 bit'
        uses: actions/upload-artifact@master
        with:
          name: osx64-${{ matrix.name }}
          path: dist/*osx64.zip

  nightly:
    needs: [linwin, mac]
    if: github.ref == 'refs/heads/moon' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: 'ğŸ“¦ Nightly'
    steps:
      - name: 'ğŸ“¥ Download artifacts'
        uses: actions/download-artifact@v2

      - name: Append GITHUB_SHA to release assets
        run: |
          for item in lin32/* lin64/* win32/* win64/*; do
            mv "$item" "${item%.*}-${GITHUB_SHA}.zip"
          done
          for name in Catalina BigSur; do
            item="$(ls osx64-$name/*)"
            mv "$item" "${item%.*}-$name-${GITHUB_SHA}.zip"
          done

      - name: 'ğŸ“¦ Run eine/tip'
        uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'nightly'
          rm: true
          files: |
            lin32/*
            lin64/*
            win32/*
            win64/*
            osx64-Catalina/*
            osx64-BigSur/*

#---

# Generated artifacts (depending on the platform) are:
# - dist/*.zip
# - dist/*.AppImage
# - dist/*.exe
# - dist/*.dmg
